# Generated by Django 6.1.1 on 2026-10-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="contact",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Фамилия"),
        ),
        migrations.AddField(
            model_name="contact",
            name="patronymic",
            field=models.CharField(blank=True, max_length=50, verbose_name="Отчество"),
        ),
    ]
